apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: policy-subscription
  namespace: policie
  annotations:
    apps.open-cluster-management.io/github-path: policy/namespace
    apps.open-cluster-management.io/github-branch: master
spec:
  hooksecretref: 
    name: toweraccess
  channel: policies/etcdtest
  placement:
   local: true
